### ISSUE TITLE
Unexpected input(s) 'distribution-type'

### ISSUE THREAD

**Issue by leovms** [Azure/build-vm-image#4]
In the [README.md](https://github.com/Azure/build-vm-image/blob/master/README.md), in the section [Sample workflow to create a custom Ubuntu OS image and distribute through Shared Image Gallery](https://github.com/Azure/build-vm-image/blob/master/README.md#sample-workflow-to-create-a-custom-ubuntu-os-image-and-distribute-through-shared-image-gallery), the property `distributor-type` should be changed to `dist-type`. This should be changed throughout the document.

Optionally, consider making such a discrepancy throw an error, instead of a warning, in the workflow, that then defaults to using `ManagedImage`. It took a few cycles to understand why an image was being created.

> Warning: Unexpected input(s) 'distributor-type', valid inputs are ['location', 'resource-group-name', 'image-builder-template-name', 'build-timeout-in-minutes', 'vm-size', 'managed-identity', 'source-image-type', 'source-os-type', 'source-image', 'customizer-source', 'customizer-script', 'customizer-windows-update', 'dist-type', 'dist-resource-id', 'dist-location', 'run-output-name', 'dist-image-tags']

**Comment by raiyanalam** [comment]
Thanks Leo for pointing out the issue. We have updated the readme file. 
We will look into the suggestion for preference between error/warning and follow the same across all actions.
Closing this issue.
